// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import {
  TrainingExample,
  TranslationOutput,
  ModerationResult,
  AIDetectionOutput,
  FakeVoiceDetectionOutput,
  SummarizationOutput,
  SentimentOutput,
  CategorizationOutput
} from '../../types';

/**
 * Collects training data from various factory outputs by converting them into TrainingExample format
 * This function simulates collecting data from different MCF services to create training datasets
 */
export function collectFromFactories(): TrainingExample[] {
  const examples: TrainingExample[] = [];

  // Collect from translation outputs
  examples.push(...collectTranslationExamples());

  // Collect from moderation outputs
  examples.push(...collectModerationExamples());

  // Collect from detection outputs
  examples.push(...collectDetectionExamples());

  // Collect from agent outputs
  examples.push(...collectAgentExamples());

  return examples;
}

/**
 * Generate training examples from translation factory outputs
 */
function collectTranslationExamples(): TrainingExample[] {
  const examples: TrainingExample[] = [];

  // Simulated translation outputs for training data
  const translationOutputs: TranslationOutput[] = [
    {
      translated: "Hello, how are you?",
      sourceLang: "en",
      targetLang: "es",
      provider: "openai",
      tokens: 45
    },
    {
      translated: "Bonjour, comment allez-vous?",
      sourceLang: "en",
      targetLang: "fr",
      provider: "anthropic",
      tokens: 38
    },
    {
      translated: "Guten Tag, wie geht es Ihnen?",
      sourceLang: "en",
      targetLang: "de",
      provider: "gemini",
      tokens: 52
    }
  ];

  translationOutputs.forEach((output, index) => {
    examples.push({
      input: `Translate "Hello, how are you?" from ${output.sourceLang} to ${output.targetLang}`,
      output: output.translated,
      task: "translation",
      metadata: {
        sourceLang: output.sourceLang,
        targetLang: output.targetLang,
        provider: output.provider,
        tokens: output.tokens,
        factory: "translation",
        exampleId: `translation_${index}`
      }
    });
  });

  return examples;
}

/**
 * Generate training examples from moderation factory outputs
 */
function collectModerationExamples(): TrainingExample[] {
  const examples: TrainingExample[] = [];

  // Simulated moderation outputs for training data
  const moderationOutputs: ModerationResult[] = [
    {
      safe: true,
      categories: [],
      confidence: 0.95,
      flagged: false
    },
    {
      safe: false,
      categories: ["hate_speech", "violence"],
      confidence: 0.87,
      flagged: true
    },
    {
      safe: false,
      categories: ["sexual_content"],
      confidence: 0.92,
      flagged: true
    }
  ];

  const sampleTexts = [
    "This is a normal, safe message about the weather.",
    "I hate all people from that group and wish violence upon them.",
    "This content contains explicit sexual material."
  ];

  moderationOutputs.forEach((output, index) => {
    examples.push({
      input: sampleTexts[index],
      output: JSON.stringify({
        safe: output.safe,
        categories: output.categories,
        confidence: output.confidence,
        flagged: output.flagged
      }),
      task: "moderation",
      metadata: {
        safe: output.safe,
        categories: output.categories,
        confidence: output.confidence,
        flagged: output.flagged,
        factory: "moderation",
        exampleId: `moderation_${index}`
      }
    });
  });

  return examples;
}

/**
 * Generate training examples from detection factory outputs
 */
function collectDetectionExamples(): TrainingExample[] {
  const examples: TrainingExample[] = [];

  // Simulated AI detection outputs
  const aiDetectionOutputs: AIDetectionOutput[] = [
    {
      isAI: true,
      confidence: 0.89,
      features: {
        entropy: 3.45,
        perplexity: 25.6,
        stylometry: { formality: 0.8, complexity: 0.7 }
      }
    },
    {
      isAI: false,
      confidence: 0.12,
      features: {
        entropy: 4.12,
        perplexity: 18.3,
        stylometry: { formality: 0.4, complexity: 0.5 }
      }
    }
  ];

  const aiSampleTexts = [
    "In the realm of artificial intelligence, machine learning algorithms have revolutionized the way we process and analyze vast amounts of data, enabling unprecedented insights and predictive capabilities across various domains.",
    "Hey guys, what's up? I was just thinking about grabbing some pizza later, anyone wanna join?"
  ];

  aiDetectionOutputs.forEach((output, index) => {
    examples.push({
      input: aiSampleTexts[index],
      output: JSON.stringify({
        isAI: output.isAI,
        confidence: output.confidence,
        features: output.features
      }),
      task: "ai_detection",
      metadata: {
        isAI: output.isAI,
        confidence: output.confidence,
        features: output.features,
        factory: "detection",
        detectionType: "ai",
        exampleId: `ai_detection_${index}`
      }
    });
  });

  // Simulated fake voice detection outputs
  const voiceDetectionOutputs: FakeVoiceDetectionOutput[] = [
    {
      isFake: true,
      confidence: 0.76,
      details: { spectral_artifacts: "present", timing_anomalies: "detected" }
    },
    {
      isFake: false,
      confidence: 0.08,
      details: { natural_variations: "present", human_characteristics: "confirmed" }
    }
  ];

  voiceDetectionOutputs.forEach((output, index) => {
    examples.push({
      input: `Audio buffer analysis for voice sample ${index + 1}`,
      output: JSON.stringify({
        isFake: output.isFake,
        confidence: output.confidence,
        details: output.details
      }),
      task: "voice_detection",
      metadata: {
        isFake: output.isFake,
        confidence: output.confidence,
        details: output.details,
        factory: "detection",
        detectionType: "voice",
        exampleId: `voice_detection_${index}`
      }
    });
  });

  return examples;
}

/**
 * Generate training examples from agent factory outputs
 */
function collectAgentExamples(): TrainingExample[] {
  const examples: TrainingExample[] = [];

  // Simulated summarization outputs
  const summarizationOutputs: SummarizationOutput[] = [
    {
      summary: "The article discusses climate change impacts on coastal cities, emphasizing rising sea levels and increased storm frequency.",
      length: "medium"
    },
    {
      summary: "ML algorithms process data to find patterns and make predictions.",
      length: "short"
    }
  ];

  const summaryTexts = [
    "Climate change is causing significant environmental changes worldwide. Rising temperatures are leading to melting glaciers, rising sea levels, and more frequent extreme weather events. Coastal cities face particular risks from flooding and storm surges. Scientists predict that without immediate action, many populated areas could become uninhabitable within decades. Adaptation strategies include building sea walls, relocating infrastructure, and developing resilient urban planning.",
    "Machine learning is a subset of artificial intelligence that enables computers to learn from data without being explicitly programmed. Various algorithms exist including supervised learning, unsupervised learning, and reinforcement learning. These techniques are used in applications ranging from image recognition to natural language processing."
  ];

  summarizationOutputs.forEach((output, index) => {
    examples.push({
      input: summaryTexts[index],
      output: output.summary,
      task: "summarization",
      metadata: {
        summaryLength: output.length,
        factory: "agent",
        agentType: "summarization",
        exampleId: `summarization_${index}`
      }
    });
  });

  // Simulated sentiment analysis outputs
  const sentimentOutputs: SentimentOutput[] = [
    { label: "positive", score: 0.91 },
    { label: "negative", score: 0.84 },
    { label: "neutral", score: 0.52 }
  ];

  const sentimentTexts = [
    "I absolutely love this new feature! It's amazing and works perfectly.",
    "This product is terrible. I'm very disappointed and want a refund.",
    "The weather today is neither good nor bad, just average."
  ];

  sentimentOutputs.forEach((output, index) => {
    examples.push({
      input: sentimentTexts[index],
      output: JSON.stringify({
        label: output.label,
        score: output.score
      }),
      task: "sentiment_analysis",
      metadata: {
        sentiment: output.label,
        confidence: output.score,
        factory: "agent",
        agentType: "sentiment",
        exampleId: `sentiment_${index}`
      }
    });
  });

  // Simulated categorization outputs
  const categorizationOutputs: CategorizationOutput[] = [
    {
      tags: ["technology", "AI", "machine learning", "innovation"],
      category: "Technology"
    },
    {
      tags: ["health", "fitness", "exercise", "wellness"],
      category: "Health & Fitness"
    }
  ];

  const categorizationTexts = [
    "The latest advancements in artificial intelligence and machine learning are transforming industries across the globe.",
    "Regular exercise and proper nutrition are essential for maintaining good health and preventing chronic diseases."
  ];

  categorizationOutputs.forEach((output, index) => {
    examples.push({
      input: categorizationTexts[index],
      output: JSON.stringify({
        tags: output.tags,
        category: output.category
      }),
      task: "categorization",
      metadata: {
        tags: output.tags,
        category: output.category,
        factory: "agent",
        agentType: "categorization",
        exampleId: `categorization_${index}`
      }
    });
  });

  return examples;
}
