// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

export class ValidationErrors {
  static create(): Error {
    return new Error('');
  }
}
