// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { AgentFactory } from '../../../core/factories/AgentFactory';
import { SentimentInput, SentimentOutput } from '../../../types';

const factory = new AgentFactory();

export async function analyzeSentiment(text: string): Promise<SentimentOutput> {
  const input: SentimentInput = {
    text,
    type: 'sentiment'
  };

  return await factory.run(input);
}

export async function getSentimentLabel(text: string): Promise<string> {
  const result = await analyzeSentiment(text);
  return result.label;
}

export async function getSentimentScore(text: string): Promise<number> {
  const result = await analyzeSentiment(text);
  return result.score;
}
