// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

export const STEP_TYPES = {
  TRANSLATION: 'translation',
  DETECTION: 'detection',
  MODERATION: 'moderation',
  AGENT: 'agent'
};
