#!/usr/bin/env ts-node

/**
 * Test script to verify the training pipeline works end-to-end
 */

import * as dotenv from 'dotenv';

// Load environment variables from .env file
dotenv.config();

// Initialize providers (this ensures all AI providers are registered)
import '../src/index';


import { collectFromFactories } from '../src/core/training/collectFromFactories';
import { generateLabels } from '../src/core/training/labelGenerator';
import { formatJSONL } from '../src/core/training/jsonlFormatter';
import { formatCSV } from '../src/core/training/csvFormatter';
import { formatParquet } from '../src/core/training/parquetFormatter';
import { manageShards } from '../src/core/training/shardManager';
import { generateEmbeddingsForExamples } from '../src/core/training/embeddingGenerator';
import { validateDataset } from '../src/core/training/datasetValidator';
import { generateManifest } from '../src/core/training/trainingManifestGenerator';
import { scheduleExport, runExport } from '../src/core/training/exportScheduler';

async function testTrainingPipeline() {
  console.log('🧪 Testing MCFactory Training Pipeline End-to-End\n');

  try {
    // Step 1: Collect training data from factories
    console.log('📊 Step 1: Collecting training data from factories...');
    const examples = collectFromFactories();
    console.log(`✅ Collected ${examples.length} training examples\n`);

    // Step 2: Generate labels
    console.log('🏷️  Step 2: Generating labels...');
    const labeledExamples = generateLabels(examples);
    console.log(`✅ Generated labels for ${labeledExamples.length} examples\n`);

    // Step 3: Validate dataset
    console.log('🔍 Step 3: Validating dataset...');
    const validationResult = validateDataset(labeledExamples);
    console.log(`✅ Validation ${validationResult.valid ? 'PASSED' : 'FAILED'}`);
    console.log(`   - Valid examples: ${validationResult.stats.validExamples}`);
    console.log(`   - Errors: ${validationResult.stats.errorCount}`);
    console.log(`   - Warnings: ${validationResult.stats.warningCount}\n`);

    if (!validationResult.valid) {
      console.log('❌ Dataset validation failed. Stopping test.');
      return;
    }

    // Step 4: Apply sharding
    console.log('🗂️  Step 4: Applying dataset sharding...');
    const shardedData = manageShards(labeledExamples, { maxShardSize: 5 });
    console.log(`✅ Created ${shardedData.shards.length} shards`);
    console.log(`   - Total shards: ${shardedData.shards.length}`);
    console.log(`   - Average shard size: ${Math.round(labeledExamples.length / shardedData.shards.length)}\n`);

    // Step 5: Format data (JSONL, CSV, Parquet)
    console.log('📄 Step 5: Formatting data...');

    // JSONL format
    const jsonlData = formatJSONL(shardedData.shards[0]);
    console.log(`✅ JSONL format: ${jsonlData.split('\n').filter((line: string) => line.trim()).length} lines`);

    // CSV format
    const csvData = formatCSV(shardedData.shards[0]);
    console.log(`✅ CSV format: ${csvData.split('\n').filter((line: string) => line.trim()).length} rows`);

    // Parquet format (structured data)
    const parquetData = formatParquet(shardedData.shards[0]);
    console.log(`✅ Parquet format: ${parquetData.rows.length} rows, ${parquetData.schema.fields.length} fields\n`);

    // Step 6: Generate embeddings
    console.log('🧠 Step 6: Embedding generation...');
    try {
      const apiKey = process.env.OPENAI_API_KEY;
      if (!apiKey) {
        console.log('⚠️  OPENAI_API_KEY not found in .env file. Skipping embedding generation.\n');
      } else {
        console.log('🔑 OpenAI API key found. Generating embeddings...');
        const embeddingResult = await generateEmbeddingsForExamples(
          shardedData.shards[0].slice(0, 2),
          { provider: 'embedding', fields: ['input'] }
        );
        console.log(`✅ Generated embeddings for ${embeddingResult.embeddings.length} examples`);
        console.log(`   - Dimensions: ${embeddingResult.dimensions}\n`);
      }
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      console.log('❌ Embedding generation failed:', errorMessage);
      console.log('   (This may be due to API rate limits or connectivity issues)\n');
    }

    // Step 7: Generate manifest
    console.log('📋 Step 7: Generating training manifest...');
    const manifest = generateManifest(labeledExamples, {
      datasetId: 'test_dataset',
      description: 'Test dataset generated by MCFactory training pipeline',
      includeExamples: false
    });
    console.log(`✅ Generated manifest for dataset: ${manifest.datasetId}`);
    console.log(`   - Version: ${manifest.version}`);
    console.log(`   - Total examples: ${manifest.statistics.totalExamples}`);
    console.log(`   - Tasks: ${manifest.statistics.totalTasks}`);
    console.log(`   - Completeness score: ${(manifest.quality.completenessScore * 100).toFixed(1)}%\n`);

    // Step 8: Test export scheduler (schedule a manual export)
    console.log('📅 Step 8: Testing export scheduler...');
    const jobId = scheduleExport('Test Export Job', 'manual', {
      format: 'jsonl',
      shardSize: 5,
      schedule: 'manual'
    });
    console.log(`✅ Scheduled export job: ${jobId}`);

    // Run the export
    console.log('🚀 Running export...');
    const exportResult = await runExport(jobId);
    console.log(`✅ Export ${exportResult.success ? 'SUCCEEDED' : 'FAILED'}`);
    console.log(`   - Files generated: ${exportResult.files.length}`);
    console.log(`   - Examples processed: ${exportResult.stats.examplesProcessed}`);
    console.log(`   - Duration: ${exportResult.stats.duration}ms\n`);

    // Final summary
    console.log('🎉 Training Pipeline Test Complete!');
    console.log('=====================================');
    console.log(`📊 Total Examples: ${examples.length}`);
    console.log(`🏷️  Labeled Examples: ${labeledExamples.length}`);
    console.log(`🗂️  Shards Created: ${shardedData.shards.length}`);
    console.log(`📄 Files Generated: ${exportResult.files.length}`);
    console.log(`✅ Pipeline Status: SUCCESS`);

  } catch (error) {
    console.error('❌ Training pipeline test failed:', error);
    process.exit(1);
  }
}

// Run the test
testTrainingPipeline().catch(console.error);
