// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { DetectionFactory } from '../../../core/factories/DetectionFactory';
import { AIDetectionInput, AIDetectionOutput } from '../../../types';

const factory = new DetectionFactory();

export async function detectAI(text: string): Promise<boolean> {
  const input: AIDetectionInput = {
    text
  };

  const result: AIDetectionOutput = await factory.run(input);
  return result.isAI;
}

export async function detectAIWithConfidence(text: string): Promise<AIDetectionOutput> {
  const input: AIDetectionInput = {
    text
  };

  return await factory.run(input);
}
