// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { DetectionFactory } from '../../../core/factories/DetectionFactory';
import { AIDetectionInput, AIDetectionOutput } from '../../../types';

const factory = new DetectionFactory();

/**
 * Calculate Shannon entropy of text based on character frequency
 */
export function calculateEntropy(text: string): number {
  if (!text || text.length === 0) {
    return 0;
  }

  const charCounts: { [key: string]: number } = {};
  const len = text.length;

  // Count character frequencies
  for (const char of text) {
    charCounts[char] = (charCounts[char] || 0) + 1;
  }

  // Calculate entropy using Shannon formula
  let entropy = 0;
  for (const count of Object.values(charCounts)) {
    const probability = count / len;
    entropy -= probability * Math.log2(probability);
  }

  return entropy;
}

/**
 * Get entropy from AI detection analysis (more sophisticated analysis)
 */
export async function analyzeEntropy(text: string): Promise<number> {
  const input: AIDetectionInput = {
    text
  };

  const result: AIDetectionOutput = await factory.run(input);
  return result.features?.entropy || calculateEntropy(text);
}
