// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { DetectionFactory } from '../../../core/factories/DetectionFactory';
import { AIDetectionInput, AIDetectionOutput } from '../../../types';

const factory = new DetectionFactory();

export interface StylometryFeatures {
  sentenceLength: number;
  wordLength: number;
  vocabularyRichness: number;
  punctuationDensity: number;
  [key: string]: number;
}

export async function analyzeStylometry(text: string): Promise<StylometryFeatures> {
  const input: AIDetectionInput = {
    text
  };

  const result: AIDetectionOutput = await factory.run(input);

  // Extract stylometry features from the detection result
  return (result.features?.stylometry as StylometryFeatures) || {};
}

export async function calculateStylometryFeatures(text: string): Promise<StylometryFeatures> {
  // Basic stylometry calculations
  const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 0);
  const words = text.split(/\s+/).filter(w => w.length > 0);

  const sentenceLengths = sentences.map(s => s.trim().split(/\s+/).length);
  const wordLengths = words.map(w => w.length);

  return {
    sentenceLength: sentenceLengths.reduce((a, b) => a + b, 0) / sentenceLengths.length || 0,
    wordLength: wordLengths.reduce((a, b) => a + b, 0) / wordLengths.length || 0,
    vocabularyRichness: new Set(words.map(w => w.toLowerCase())).size / words.length || 0,
    punctuationDensity: (text.match(/[.,!?;:]/g) || []).length / text.length || 0
  };
}
