// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import axios, { AxiosError } from 'axios';
import { Provider, ProviderRequest, ProviderResponse } from '../../types';
import { ProviderRegistry } from './providerRegistry';
import { PROVIDER_TYPES } from './providerTypes';

export class CohereProvider implements Provider {
  name = PROVIDER_TYPES.COHERE;

  async callModel(req: ProviderRequest): Promise<ProviderResponse> {
    const apiKey = process.env.COHERE_API_KEY;
    if (!apiKey) {
      throw new Error('COHERE_API_KEY environment variable is required');
    }

    try {
      // Convert messages to Cohere format
      const messages = Array.isArray(req.input) ? req.input : [{ role: 'user', message: req.input as string }];

      const response = await axios.post(
        'https://api.cohere.ai/v1/chat',
        {
          model: req.model,
          message: messages.length > 0 ? messages[messages.length - 1].message || messages[messages.length - 1].content : '',
          chat_history: messages.slice(0, -1).map(msg => ({
            role: msg.role,
            message: msg.message || msg.content
          })),
          ...req.options,
        },
        {
          headers: {
            'Authorization': `Bearer ${apiKey}`,
            'Content-Type': 'application/json',
          },
        }
      );

      const data = response.data;
      return {
        output: data.text,
        tokens: data.meta?.tokens?.input_tokens + data.meta?.tokens?.output_tokens,
        model: req.model,
        provider: this.name,
      };
    } catch (error) {
      if (error instanceof AxiosError) {
        throw new Error(`Cohere API error: ${error.response?.data?.message || error.message}`);
      }
      throw new Error(`Cohere provider error: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  static create(): Provider {
    const provider = new CohereProvider();
    ProviderRegistry.registerProvider(provider);
    return provider;
  }
}
