// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import axios, { AxiosError } from 'axios';
import { Provider, ProviderRequest, ProviderResponse } from '../../types';
import { ProviderRegistry } from './providerRegistry';
import { PROVIDER_TYPES } from './providerTypes';

export class ElevenLabsProvider implements Provider {
  name = PROVIDER_TYPES.ELEVENLABS;

  async callModel(req: ProviderRequest): Promise<ProviderResponse> {
    const apiKey = process.env.ELEVENLABS_API_KEY;
    if (!apiKey) {
      throw new Error('ELEVENLABS_API_KEY environment variable is required');
    }

    try {
      const voiceId = req.options?.voice_id || '21m00Tcm4TlvDq8ikWAM'; // Default voice
      const response = await axios.post(
        `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`,
        {
          text: req.input as string,
          model_id: req.model || 'eleven_monolingual_v1',
          voice_settings: {
            stability: req.options?.stability || 0.5,
            similarity_boost: req.options?.similarity_boost || 0.5,
            ...req.options?.voice_settings,
          },
        },
        {
          headers: {
            'Accept': 'audio/mpeg',
            'Content-Type': 'application/json',
            'xi-api-key': apiKey,
          },
          responseType: 'arraybuffer',
        }
      );

      // Convert buffer to ArrayBuffer for consistency
      const audioBuffer = new Uint8Array(response.data).buffer;

      return {
        output: audioBuffer,
        model: req.model || 'eleven_monolingual_v1',
        provider: this.name,
      };
    } catch (error) {
      if (error instanceof AxiosError) {
        throw new Error(`ElevenLabs API error: ${error.response?.data?.message || error.message}`);
      }
      throw new Error(`ElevenLabs provider error: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  static create(): Provider {
    const provider = new ElevenLabsProvider();
    ProviderRegistry.registerProvider(provider);
    return provider;
  }
}
