// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import axios, { AxiosError } from 'axios';
import { Provider, ProviderRequest, ProviderResponse, EmbeddingRequest, EmbeddingResponse } from '../../types';
import { ProviderRegistry } from './providerRegistry';
import { PROVIDER_TYPES } from './providerTypes';

export class EmbeddingProvider implements Provider {
  name = PROVIDER_TYPES.EMBEDDING;

  async callModel(req: ProviderRequest): Promise<ProviderResponse> {
    // Determine which API to use based on model or options
    const embeddingReq = req.input as EmbeddingRequest;
    const provider = req.options?.provider || 'openai';

    try {
      let response;
      let embedding: number[];
      let dimensions: number;

      if (provider === 'openai') {
        const apiKey = process.env.OPENAI_API_KEY;
        if (!apiKey) {
          throw new Error('OPENAI_API_KEY environment variable is required for embeddings');
        }

        response = await axios.post(
          'https://api.openai.com/v1/embeddings',
          {
            input: embeddingReq.text,
            model: req.model || 'text-embedding-ada-002',
            ...req.options,
          },
          {
            headers: {
              'Authorization': `Bearer ${apiKey}`,
              'Content-Type': 'application/json',
            },
          }
        );

        const data = response.data;
        embedding = data.data[0].embedding;
        dimensions = embedding.length;

        return {
          output: { embedding, dimensions },
          tokens: data.usage?.total_tokens,
          model: req.model || 'text-embedding-ada-002',
          provider: this.name,
        };

      } else if (provider === 'cohere') {
        const apiKey = process.env.COHERE_API_KEY;
        if (!apiKey) {
          throw new Error('COHERE_API_KEY environment variable is required for embeddings');
        }

        response = await axios.post(
          'https://api.cohere.ai/v1/embed',
          {
            texts: [embeddingReq.text],
            model: req.model || 'embed-english-v2.0',
            ...req.options,
          },
          {
            headers: {
              'Authorization': `Bearer ${apiKey}`,
              'Content-Type': 'application/json',
            },
          }
        );

        const data = response.data;
        embedding = data.embeddings[0];
        dimensions = embedding.length;

        return {
          output: { embedding, dimensions },
          tokens: data.meta?.billed_units?.input_tokens,
          model: req.model || 'embed-english-v2.0',
          provider: this.name,
        };

      } else {
        throw new Error(`Unsupported embedding provider: ${provider}`);
      }
    } catch (error) {
      if (error instanceof AxiosError) {
        throw new Error(`Embedding API error: ${error.response?.data?.error?.message || error.response?.data?.message || error.message}`);
      }
      throw new Error(`Embedding provider error: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  static create(): Provider {
    const provider = new EmbeddingProvider();
    ProviderRegistry.registerProvider(provider);
    return provider;
  }
}
