// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import axios, { AxiosError } from 'axios';
import { Provider, ProviderRequest, ProviderResponse } from '../../types';
import { ProviderRegistry } from './providerRegistry';
import { PROVIDER_TYPES } from './providerTypes';

export class GeminiProvider implements Provider {
  name = PROVIDER_TYPES.GEMINI;

  async callModel(req: ProviderRequest): Promise<ProviderResponse> {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY environment variable is required');
    }

    try {
      // Convert messages format to Gemini format
      const contents = Array.isArray(req.input)
        ? req.input.map(msg => ({
            role: msg.role === 'assistant' ? 'model' : 'user',
            parts: [{ text: msg.content }]
          }))
        : [{ role: 'user', parts: [{ text: req.input as string }] }];

      const response = await axios.post(
        `https://generativelanguage.googleapis.com/v1beta/models/${req.model}:generateContent?key=${apiKey}`,
        {
          contents,
          generationConfig: {
            temperature: req.options?.temperature || 0.7,
            maxOutputTokens: req.options?.max_tokens || 1024,
            ...req.options,
          },
        },
        {
          headers: {
            'Content-Type': 'application/json',
          },
        }
      );

      const data = response.data;
      const text = data.candidates[0].content.parts[0].text;

      return {
        output: text,
        tokens: data.usageMetadata?.totalTokenCount,
        model: req.model,
        provider: this.name,
      };
    } catch (error) {
      if (error instanceof AxiosError) {
        throw new Error(`Gemini API error: ${error.response?.data?.error?.message || error.message}`);
      }
      throw new Error(`Gemini provider error: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  static create(): Provider {
    const provider = new GeminiProvider();
    ProviderRegistry.registerProvider(provider);
    return provider;
  }
}
