// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import axios, { AxiosError } from 'axios';
import { Provider, ProviderRequest, ProviderResponse } from '../../types';
import { ProviderRegistry } from './providerRegistry';
import { PROVIDER_TYPES } from './providerTypes';

export class ImageModerationProvider implements Provider {
  name = PROVIDER_TYPES.IMAGE_MODERATION;

  async callModel(req: ProviderRequest): Promise<ProviderResponse> {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      throw new Error('OPENAI_API_KEY environment variable is required for image moderation');
    }

    try {
      // Convert image buffer to base64
      const imageBuffer = req.input as ArrayBuffer;
      const base64Image = Buffer.from(imageBuffer).toString('base64');

      const response = await axios.post(
        'https://api.openai.com/v1/chat/completions',
        {
          model: req.model || 'gpt-4-vision-preview',
          messages: [
            {
              role: 'user',
              content: [
                {
                  type: 'text',
                  text: 'Analyze this image for inappropriate content. Return a JSON object with: { "safe": boolean, "categories": string[], "confidence": number, "reasoning": string }'
                },
                {
                  type: 'image_url',
                  image_url: {
                    url: `data:image/jpeg;base64,${base64Image}`
                  }
                }
              ]
            }
          ],
          max_tokens: 500,
          ...req.options,
        },
        {
          headers: {
            'Authorization': `Bearer ${apiKey}`,
            'Content-Type': 'application/json',
          },
        }
      );

      const data = response.data;
      const moderationResult = JSON.parse(data.choices[0].message.content);

      return {
        output: moderationResult,
        tokens: data.usage?.total_tokens,
        model: req.model || 'gpt-4-vision-preview',
        provider: this.name,
      };
    } catch (error) {
      if (error instanceof AxiosError) {
        throw new Error(`Image Moderation API error: ${error.response?.data?.error?.message || error.message}`);
      }
      throw new Error(`Image Moderation provider error: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  static create(): Provider {
    const provider = new ImageModerationProvider();
    ProviderRegistry.registerProvider(provider);
    return provider;
  }
}
