// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import axios, { AxiosError } from 'axios';
import { Provider, ProviderRequest, ProviderResponse } from '../../types';
import { ProviderRegistry } from './providerRegistry';
import { PROVIDER_TYPES } from './providerTypes';

export class OpenAIProvider implements Provider {
  name = PROVIDER_TYPES.OPENAI;

  async callModel(req: ProviderRequest): Promise<ProviderResponse> {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      throw new Error('OPENAI_API_KEY environment variable is required');
    }

    try {
      const response = await axios.post(
        'https://api.openai.com/v1/chat/completions',
        {
          model: req.model,
          messages: req.input,
          ...req.options,
        },
        {
          headers: {
            'Authorization': `Bearer ${apiKey}`,
            'Content-Type': 'application/json',
          },
        }
      );

      const data = response.data;
      return {
        output: data.choices[0].message.content,
        tokens: data.usage?.total_tokens,
        model: data.model,
        provider: this.name,
      };
    } catch (error) {
      if (error instanceof AxiosError) {
        throw new Error(`OpenAI API error: ${error.response?.data?.error?.message || error.message}`);
      }
      throw new Error(`OpenAI provider error: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  static create(): Provider {
    const provider = new OpenAIProvider();
    ProviderRegistry.registerProvider(provider);
    return provider;
  }
}
