// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

export const PROVIDER_TYPES = {
  OPENAI: 'openai',
  ANTHROPIC: 'anthropic',
  GEMINI: 'gemini',
  COHERE: 'cohere',
  LOCAL: 'local',
  WHISPER: 'whisper',
  ELEVENLABS: 'elevenlabs',
  IMAGE_MODERATION: 'image_moderation',
  EMBEDDING: 'embedding'
};
