// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { Provider } from '../../types';

export class ProviderRegistry {
  private static providers = new Map<string, Provider>();

  static registerProvider(provider: Provider): void {
    this.providers.set(provider.name, provider);
  }

  static get(name: string): Provider | undefined {
    return this.providers.get(name);
  }
}
