// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import axios, { AxiosError } from 'axios';
import { Provider, ProviderRequest, ProviderResponse } from '../../types';
import { ProviderRegistry } from './providerRegistry';
import { PROVIDER_TYPES } from './providerTypes';

export class WhisperProvider implements Provider {
  name = PROVIDER_TYPES.WHISPER;

  async callModel(req: ProviderRequest): Promise<ProviderResponse> {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      throw new Error('OPENAI_API_KEY environment variable is required for Whisper');
    }

    try {
      // Convert ArrayBuffer to Buffer for FormData
      const audioBuffer = req.input as ArrayBuffer;
      const buffer = Buffer.from(audioBuffer);

      const formData = new FormData();
      formData.append('file', new Blob([buffer], { type: 'audio/wav' }), 'audio.wav');
      formData.append('model', req.model || 'whisper-1');
      if (req.options?.language) {
        formData.append('language', req.options.language);
      }
      if (req.options?.response_format) {
        formData.append('response_format', req.options.response_format);
      }

      const response = await axios.post(
        'https://api.openai.com/v1/audio/transcriptions',
        formData,
        {
          headers: {
            'Authorization': `Bearer ${apiKey}`,
            // Don't set Content-Type, let axios set it with boundary for FormData
          },
        }
      );

      const data = response.data;
      return {
        output: data.text,
        model: req.model || 'whisper-1',
        provider: this.name,
      };
    } catch (error) {
      if (error instanceof AxiosError) {
        throw new Error(`Whisper API error: ${error.response?.data?.error?.message || error.message}`);
      }
      throw new Error(`Whisper provider error: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  static create(): Provider {
    const provider = new WhisperProvider();
    ProviderRegistry.registerProvider(provider);
    return provider;
  }
}
