// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { DetectionFactory } from '../../../core/factories/DetectionFactory';
import { FakeVoiceDetectionInput, FakeVoiceDetectionOutput } from '../../../types';

const factory = new DetectionFactory();

export async function detectFakeVoice(audio: Buffer): Promise<boolean> {
  // Convert Buffer to ArrayBuffer
  const audioBuffer = audio.buffer.slice(
    audio.byteOffset,
    audio.byteOffset + audio.byteLength
  ) as ArrayBuffer;

  const input: FakeVoiceDetectionInput = {
    audioBuffer
  };

  const result: FakeVoiceDetectionOutput = await factory.run(input);
  return result.isFake;
}

export async function detectFakeVoiceWithConfidence(audio: Buffer): Promise<FakeVoiceDetectionOutput> {
  // Convert Buffer to ArrayBuffer
  const audioBuffer = audio.buffer.slice(
    audio.byteOffset,
    audio.byteOffset + audio.byteLength
  ) as ArrayBuffer;

  const input: FakeVoiceDetectionInput = {
    audioBuffer
  };

  return await factory.run(input);
}
