// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import * as fs from 'fs';
import * as path from 'path';

interface MCPManifest {
  name: string;
  version: string;
  description: string;
  tools: MCPTool[];
  handlers: Record<string, any>;
}

interface MCPTool {
  name: string;
  description: string;
  inputSchema: {
    type: string;
    properties: Record<string, any>;
    required?: string[];
  };
}

const MANIFEST_PATH = 'mcp-manifest.json';

const AVAILABLE_TOOLS: MCPTool[] = [
  {
    name: 'translate-text',
    description: 'Translate text between languages',
    inputSchema: {
      type: 'object',
      properties: {
        text: { type: 'string', description: 'Text to translate' },
        targetLang: { type: 'string', description: 'Target language code (e.g., "es", "fr")' },
        sourceLang: { type: 'string', description: 'Source language code (optional)' }
      },
      required: ['text', 'targetLang']
    }
  },
  {
    name: 'detect-ai-text',
    description: 'Detect if text was generated by AI',
    inputSchema: {
      type: 'object',
      properties: {
        text: { type: 'string', description: 'Text to analyze' }
      },
      required: ['text']
    }
  },
  {
    name: 'moderate-text',
    description: 'Check text for inappropriate content',
    inputSchema: {
      type: 'object',
      properties: {
        text: { type: 'string', description: 'Text to moderate' }
      },
      required: ['text']
    }
  },
  {
    name: 'summarize-text',
    description: 'Generate a summary of the provided text',
    inputSchema: {
      type: 'object',
      properties: {
        text: { type: 'string', description: 'Text to summarize' },
        length: { type: 'string', enum: ['short', 'medium', 'long'], description: 'Summary length' }
      },
      required: ['text']
    }
  },
  {
    name: 'analyze-sentiment',
    description: 'Analyze the sentiment of text',
    inputSchema: {
      type: 'object',
      properties: {
        text: { type: 'string', description: 'Text to analyze' }
      },
      required: ['text']
    }
  },
  {
    name: 'categorize-text',
    description: 'Categorize text content',
    inputSchema: {
      type: 'object',
      properties: {
        text: { type: 'string', description: 'Text to categorize' }
      },
      required: ['text']
    }
  },
  {
    name: 'speech-to-text',
    description: 'Convert audio speech to text',
    inputSchema: {
      type: 'object',
      properties: {
        audioBuffer: { type: 'string', description: 'Base64 encoded audio buffer' },
        language: { type: 'string', description: 'Language code (optional)' }
      },
      required: ['audioBuffer']
    }
  },
  {
    name: 'text-to-speech',
    description: 'Convert text to speech audio',
    inputSchema: {
      type: 'object',
      properties: {
        text: { type: 'string', description: 'Text to convert to speech' },
        voice: { type: 'string', description: 'Voice to use (optional)' }
      },
      required: ['text']
    }
  },
  {
    name: 'ocr-image',
    description: 'Extract text from images using OCR',
    inputSchema: {
      type: 'object',
      properties: {
        imageBuffer: { type: 'string', description: 'Base64 encoded image buffer' }
      },
      required: ['imageBuffer']
    }
  },
  {
    name: 'detect-fake-voice',
    description: 'Detect if audio contains fake/synthesized voice',
    inputSchema: {
      type: 'object',
      properties: {
        audioBuffer: { type: 'string', description: 'Base64 encoded audio buffer' }
      },
      required: ['audioBuffer']
    }
  }
];

export function generateManifestCommand(): void {
  try {
    // Read package.json for version info
    const packageJsonPath = path.join(process.cwd(), 'package.json');
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

    // Create manifest
    const manifest: MCPManifest = {
      name: packageJson.name,
      version: packageJson.version,
      description: packageJson.description,
      tools: AVAILABLE_TOOLS,
      handlers: {}
    };

    // Write manifest file
    fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2));

    console.log(`✓ MCP manifest generated: ${MANIFEST_PATH}`);
    console.log(`📋 Included ${AVAILABLE_TOOLS.length} tools:`);
    AVAILABLE_TOOLS.forEach(tool => {
      console.log(`  • ${tool.name}: ${tool.description}`);
    });
    console.log('');
    console.log('Use this manifest to integrate MCF with MCP-compatible clients.');

  } catch (error) {
    console.error('✗ Failed to generate MCP manifest:', error);
    process.exit(1);
  }
}
