// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { Command } from 'commander';
import * as fs from 'fs';
import { MCFConfig, PipelineResult } from '../../../types';
import { ConfigLoader } from '../../config/configLoader';
import { PipelineRunner } from '../../orchestration/pipelineRunner';

const CONFIG_PATH = 'mcf.config.json';

export function runPipelineCommand(pipelineName: string, options: any): void {
  try {
    // Check if config exists
    if (!fs.existsSync(CONFIG_PATH)) {
      console.error(`✗ Configuration file not found: ${CONFIG_PATH}`);
      console.log('Run "mcf init" to create a default configuration.');
      process.exit(1);
    }

    // Load config
    const config = ConfigLoader.load() as MCFConfig;

    // Check if pipelines are defined
    if (!config.pipelines || !config.pipelines[pipelineName]) {
      console.error(`✗ Pipeline "${pipelineName}" not found in configuration`);
      const availablePipelines = config.pipelines ? Object.keys(config.pipelines) : [];
      if (availablePipelines.length > 0) {
        console.log(`Available pipelines: ${availablePipelines.join(', ')}`);
      } else {
        console.log('No pipelines defined in configuration.');
      }
      process.exit(1);
    }

    console.log(`🚀 Running pipeline: ${pipelineName}`);

    // Run the pipeline (PipelineRunner.run() is currently a stub)
    const result: PipelineResult = PipelineRunner.run();

    // Display results
    if (result.success) {
      console.log('✓ Pipeline completed successfully');
      if (result.data) {
        console.log('📄 Output:', result.data);
      }
    } else {
      console.error('✗ Pipeline failed');
    }

    // Display logs if any
    if (result.logs && result.logs.length > 0) {
      console.log('\n📋 Pipeline logs:');
      result.logs.forEach((log, index) => {
        console.log(`  ${index + 1}. ${log}`);
      });
    }

    // Exit with appropriate code
    process.exit(result.success ? 0 : 1);

  } catch (error) {
    console.error('✗ Failed to run pipeline:', error);
    process.exit(1);
  }
}
