// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { MediaFactory } from '../../../../core/factories/MediaFactory';
import { TTSInput, TTSOutput } from '../../../../types';

const factory = new MediaFactory();

export async function textToSpeech(text: string, voice?: string): Promise<Buffer> {
  const input: TTSInput = {
    text,
    voice
  };

  const result: TTSOutput = await factory.run(input);

  // Convert ArrayBuffer to Buffer
  return Buffer.from(result.audioBuffer);
}
