// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { ProviderRegistry } from '../../../core/providers/providerRegistry';
import { ModerationResult } from '../../../types';

export async function moderateImage(image: Buffer): Promise<ModerationResult> {
  const provider = ProviderRegistry.get('image_moderation');

  if (!provider) {
    throw new Error('Image moderation provider not found');
  }

  // Convert Buffer to ArrayBuffer
  const imageBuffer = image.buffer.slice(
    image.byteOffset,
    image.byteOffset + image.byteLength
  );

  const request = {
    model: 'gpt-4-vision-preview',
    input: imageBuffer,
    options: {
      max_tokens: 500
    }
  };

  const response = await provider.callModel(request);

  // Parse the response (similar to ModerationFactory parsing)
  try {
    const result = typeof response.output === 'string'
      ? JSON.parse(response.output)
      : response.output;

    return {
      safe: result.safe !== false,
      categories: Array.isArray(result.categories) ? result.categories : [],
      confidence: typeof result.confidence === 'number' ? result.confidence : 0.5,
      flagged: result.safe === false
    };
  } catch (error) {
    // Fallback
    return {
      safe: false,
      categories: ['analysis_failed'],
      confidence: 0.5,
      flagged: true
    };
  }
}

export async function isImageSafe(image: Buffer): Promise<boolean> {
  const result = await moderateImage(image);
  return result.safe;
}
