// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { translateText } from '../services/translation/text/translateText';
import { detectAI } from '../services/detection/text/detectAI';
import { moderateText } from '../services/moderation/text/moderateText';
import { TranslationResult, DetectionResult, ModerationResult, MCFConfig } from './interfaces';

export class MCF {
  private config?: MCFConfig;

  constructor(config?: MCFConfig) {
    this.config = config;
  }

  async translate(text: string, targetLang: string, sourceLang?: string, preserveFormat?: boolean): Promise<string> {
    if (!text || typeof text !== 'string') {
      throw new Error('Text must be a non-empty string');
    }

    if (!targetLang || typeof targetLang !== 'string') {
      throw new Error('Target language must be specified');
    }

    return await translateText(text, targetLang, sourceLang, preserveFormat);
  }

  async detectAI(text: string): Promise<boolean> {
    if (!text || typeof text !== 'string') {
      throw new Error('Text must be a non-empty string');
    }

    return await detectAI(text);
  }

  async detectAIWithDetails(text: string): Promise<DetectionResult> {
    if (!text || typeof text !== 'string') {
      throw new Error('Text must be a non-empty string');
    }

    const { detectAIWithConfidence } = await import('../services/detection/text/detectAI');
    const result = await detectAIWithConfidence(text);

    return {
      isAI: result.isAI,
      confidence: result.confidence
    };
  }

  async moderate(text: string): Promise<ModerationResult> {
    if (!text || typeof text !== 'string') {
      throw new Error('Text must be a non-empty string');
    }

    const result = await moderateText(text);

    return {
      flagged: !result.safe,
      categories: result.categories
    };
  }

  async isTextSafe(text: string): Promise<boolean> {
    if (!text || typeof text !== 'string') {
      throw new Error('Text must be a non-empty string');
    }

    const { isTextSafe } = await import('../services/moderation/text/moderateText');
    return await isTextSafe(text);
  }

  // Utility method to validate configuration
  validateConfig(): boolean {
    return !!(this.config?.provider && this.config?.apiKey);
  }

  // Method to update configuration
  updateConfig(config: MCFConfig): void {
    this.config = config;
  }
}
