// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

export * from './interfaces';

declare module 'mcf' {
  export class MCF {
    constructor(config?: MCFConfig);
    translate(text: string, targetLang: string): Promise<string>;
    detectAI(text: string): Promise<boolean>;
    moderate(text: string): Promise<ModerationResult>;
  }
}
