// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

export const PROVIDER_BINDINGS = {
  openai: 'openai',
  anthropic: 'anthropic',
  gemini: 'gemini',
  cohere: 'cohere'
};
