// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { AgentFactory } from '../../../core/factories/AgentFactory';
import { SummarizationInput, SummarizationOutput } from '../../../types';

const factory = new AgentFactory();

export async function summarize(
  text: string,
  length?: "short" | "medium" | "long"
): Promise<string> {
  const input: SummarizationInput = {
    text,
    length: length || 'medium'
  };

  const result = await factory.run(input as any) as SummarizationOutput;
  return result.summary;
}
