// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { AgentFactory } from '../../../core/factories/AgentFactory';
import { SummarizationInput, SummarizationOutput } from '../../../types';

const factory = new AgentFactory();

export interface ThreadMessage {
  author?: string;
  content: string;
  timestamp?: string | Date;
}

export async function summarizeThread(
  messages: ThreadMessage[],
  length?: "short" | "medium" | "long"
): Promise<string> {
  // Format messages as a thread
  const threadText = messages
    .map((msg, index) => {
      const author = msg.author || `User ${index + 1}`;
      const timestamp = msg.timestamp
        ? (typeof msg.timestamp === 'string' ? msg.timestamp : msg.timestamp.toISOString())
        : '';
      return `${author}${timestamp ? ` (${timestamp})` : ''}: ${msg.content}`;
    })
    .join('\n\n');

  const input: SummarizationInput = {
    text: `Thread Summary:\n\n${threadText}`,
    length: length || 'medium'
  };

  const result = await factory.run(input as any) as SummarizationOutput;
  return result.summary;
}
