// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { MediaFactory } from '../../../../core/factories/MediaFactory';
import { STTInput, STTOutput } from '../../../../types';

const factory = new MediaFactory();

export async function speechToText(audio: Buffer, language?: string): Promise<string> {
  // Convert Buffer to ArrayBuffer
  const audioBuffer = audio.buffer.slice(
    audio.byteOffset,
    audio.byteOffset + audio.byteLength
  ) as ArrayBuffer;

  const input: STTInput = {
    audioBuffer,
    language
  };

  const result: STTOutput = await factory.run(input);
  return result.text;
}
