// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { ModerationFactory } from '../../../core/factories/ModerationFactory';
import { ModerationInput, ModerationResult } from '../../../types';

const factory = new ModerationFactory();

export async function moderateText(text: string): Promise<ModerationResult> {
  const input: ModerationInput = {
    text
  };

  return await factory.run(input);
}

export async function isTextSafe(text: string): Promise<boolean> {
  const result = await moderateText(text);
  return result.safe;
}
