// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { TranslationFactory } from '../../core/factories/TranslationFactory';

const factory = new TranslationFactory();

export async function formalize(text: string, context?: string): Promise<string> {
  const contextPrompt = context ? ` in a ${context} context` : '';
  const formalizePrompt = `Rewrite the following text in a formal, professional tone${contextPrompt}. Use appropriate business/academic language, avoid contractions, slang, and colloquial expressions. Maintain the original meaning and key information:`;

  const input = {
    text: `${formalizePrompt}\n\n${text}`,
    targetLang: 'en'
  };

  const result = await factory.run(input);
  return result.translated;
}
