// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { TranslationFactory } from '../../core/factories/TranslationFactory';

const factory = new TranslationFactory();

export async function rewrite(text: string, style?: string): Promise<string> {
  const rewritePrompt = style
    ? `Rewrite the following text in a ${style} style while preserving the original meaning and key information:`
    : `Rewrite the following text in a different way while preserving the original meaning and key information:`;

  const input = {
    text: `${rewritePrompt}\n\n${text}`,
    targetLang: 'en' // Rewriting is typically in the same language
  };

  const result = await factory.run(input);
  return result.translated;
}
