// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { TranslationFactory } from '../../core/factories/TranslationFactory';

const factory = new TranslationFactory();

export interface SEORewriteOptions {
  keywords?: string[];
  targetAudience?: string;
  contentType?: 'blog' | 'article' | 'product' | 'landing';
}

export async function seoRewrite(
  text: string,
  options: SEORewriteOptions = {}
): Promise<string> {
  const { keywords, targetAudience, contentType } = options;

  let seoPrompt = `Rewrite the following text with SEO best practices in mind. Optimize for search engines while maintaining readability and value:`;

  if (keywords && keywords.length > 0) {
    seoPrompt += `\n\nIncorporate these keywords naturally: ${keywords.join(', ')}`;
  }

  if (targetAudience) {
    seoPrompt += `\n\nTarget audience: ${targetAudience}`;
  }

  if (contentType) {
    seoPrompt += `\n\nContent type: ${contentType} post`;
  }

  seoPrompt += `\n\nFocus on:
- Natural keyword integration
- Engaging headings and subheadings
- Clear, scannable content structure
- Value-driven content
- Internal linking opportunities
- User intent satisfaction

Original text:`;

  const input = {
    text: `${seoPrompt}\n\n${text}`,
    targetLang: 'en'
  };

  const result = await factory.run(input);
  return result.translated;
}
