// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { TranslationFactory } from '../../core/factories/TranslationFactory';

const factory = new TranslationFactory();

export async function simplify(text: string, level?: 'basic' | 'intermediate' | 'advanced'): Promise<string> {
  const levelDesc = {
    basic: 'use very simple words and short sentences',
    intermediate: 'use simpler words and clearer sentence structure',
    advanced: 'maintain some complexity but improve clarity'
  };

  const simplifyPrompt = level
    ? `Simplify the following text for easier understanding. ${levelDesc[level]}. Keep the essential meaning and information intact:`
    : `Simplify the following text to make it easier to understand while preserving the original meaning and key information:`;

  const input = {
    text: `${simplifyPrompt}\n\n${text}`,
    targetLang: 'en'
  };

  const result = await factory.run(input);
  return result.translated;
}
