// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { TranslationFactory } from '../../core/factories/TranslationFactory';

const factory = new TranslationFactory();

export type ToneType =
  | 'formal'
  | 'casual'
  | 'friendly'
  | 'professional'
  | 'enthusiastic'
  | 'sarcastic'
  | 'serious'
  | 'humorous'
  | 'persuasive'
  | 'empathetic';

export async function convertTone(text: string, tone: ToneType): Promise<string> {
  const toneDescriptions = {
    formal: 'formal and professional',
    casual: 'casual and relaxed',
    friendly: 'warm and friendly',
    professional: 'business professional',
    enthusiastic: 'excited and energetic',
    sarcastic: 'sarcastically witty',
    serious: 'serious and straightforward',
    humorous: 'light-hearted and funny',
    persuasive: 'convincing and persuasive',
    empathetic: 'understanding and compassionate'
  };

  const toneDesc = toneDescriptions[tone] || tone;
  const convertPrompt = `Rewrite the following text in a ${toneDesc} tone. Adapt the language, word choice, and style to match the desired tone while preserving the original meaning and key information:`;

  const input = {
    text: `${convertPrompt}\n\n${text}`,
    targetLang: 'en'
  };

  const result = await factory.run(input);
  return result.translated;
}
