// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { MediaFactory } from '../../core/factories/MediaFactory';
import { ImageCaptionInput, ImageCaptionOutput } from '../../types';

const factory = new MediaFactory();

export async function captionImage(image: Buffer): Promise<string> {
  // Convert Buffer to ArrayBuffer
  const imageBuffer = image.buffer.slice(
    image.byteOffset,
    image.byteOffset + image.byteLength
  ) as ArrayBuffer;

  const input: ImageCaptionInput = {
    imageBuffer,
    type: 'caption'
  };

  const result: ImageCaptionOutput = await factory.run(input);
  return result.caption;
}

export async function captionImageWithConfidence(image: Buffer): Promise<ImageCaptionOutput> {
  // Convert Buffer to ArrayBuffer
  const imageBuffer = image.buffer.slice(
    image.byteOffset,
    image.byteOffset + image.byteLength
  ) as ArrayBuffer;

  const input: ImageCaptionInput = {
    imageBuffer,
    type: 'caption'
  };

  return await factory.run(input);
}
