// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { MediaFactory } from '../../core/factories/MediaFactory';
import { OCRInput, OCROutput } from '../../types';

const factory = new MediaFactory();

export async function performOCR(image: Buffer): Promise<string> {
  // Convert Buffer to ArrayBuffer
  const imageBuffer = image.buffer.slice(
    image.byteOffset,
    image.byteOffset + image.byteLength
  ) as ArrayBuffer;

  const input: OCRInput = {
    imageBuffer,
    type: 'ocr'
  };

  const result: OCROutput = await factory.run(input);
  return result.text;
}

export async function performOCRWithBlocks(image: Buffer): Promise<OCROutput> {
  // Convert Buffer to ArrayBuffer
  const imageBuffer = image.buffer.slice(
    image.byteOffset,
    image.byteOffset + image.byteLength
  ) as ArrayBuffer;

  const input: OCRInput = {
    imageBuffer,
    type: 'ocr'
  };

  return await factory.run(input);
}
