// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { MediaFactory } from '../../../../core/factories/MediaFactory';
import { TranslationFactory } from '../../../../core/factories/TranslationFactory';
import { STTInput, STTOutput, TTSInput, TTSOutput, TranslationInput, TranslationOutput } from '../../../../types';

const mediaFactory = new MediaFactory();
const translationFactory = new TranslationFactory();

export async function voiceToVoiceTranslate(
  audio: Buffer,
  targetLang: string,
  sourceLang?: string
): Promise<Buffer> {
  // Step 1: Convert audio to text (STT)
  const audioBuffer = audio.buffer.slice(
    audio.byteOffset,
    audio.byteOffset + audio.byteLength
  ) as ArrayBuffer;

  const sttInput: STTInput = {
    audioBuffer,
    language: sourceLang
  };

  const sttResult: STTOutput = await mediaFactory.run(sttInput);
  const originalText = sttResult.text;

  // Step 2: Translate the text
  const translationInput: TranslationInput = {
    text: originalText,
    sourceLang: sttResult.language || sourceLang,
    targetLang,
    preserveFormat: true
  };

  const translationResult: TranslationOutput = await translationFactory.run(translationInput);
  const translatedText = translationResult.translated;

  // Step 3: Convert translated text back to speech (TTS)
  const ttsInput: TTSInput = {
    text: translatedText
  };

  const ttsResult: TTSOutput = await mediaFactory.run(ttsInput);

  // Convert ArrayBuffer to Buffer
  return Buffer.from(ttsResult.audioBuffer);
}
