// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import {
  Factory,
  TranslationInput,
  TranslationOutput,
  FactoryOptions,
  ProviderRequest,
  ProviderResponse
} from '../../types';
import { ProviderRegistry } from '../providers/providerRegistry';

export class TranslationFactory implements Factory<TranslationInput, TranslationOutput> {
  async run(input: TranslationInput, options?: FactoryOptions): Promise<TranslationOutput> {
    const providerName = options?.provider || 'openai';
    const provider = ProviderRegistry.get(providerName);

    if (!provider) {
      throw new Error(`Provider ${providerName} not found`);
    }

    // Build the translation prompt
    const prompt = this.buildTranslationPrompt(input);

    const request: ProviderRequest = {
      model: 'gpt-4', // Default model, could be overridden by provider config
      input: prompt,
      options: {
        temperature: 0.3,
        max_tokens: 1000,
        ...options?.metadata
      }
    };

    const response: ProviderResponse = await provider.callModel(request);

    return this.parseTranslationResponse(response, input);
  }

  private buildTranslationPrompt(input: TranslationInput): string {
    const { text, sourceLang, targetLang, preserveFormat } = input;

    let prompt = `Translate the following text to ${targetLang}`;

    if (sourceLang) {
      prompt += ` from ${sourceLang}`;
    }

    if (preserveFormat) {
      prompt += '. Preserve the original formatting, structure, and any special characters.';
    }

    prompt += `:\n\n${text}`;

    return prompt;
  }

  private parseTranslationResponse(response: ProviderResponse, input: TranslationInput): TranslationOutput {
    // Extract the translated text from the provider response
    // This is a simplified implementation - in practice, you'd need more sophisticated parsing
    const translated = typeof response.output === 'string'
      ? response.output.trim()
      : JSON.stringify(response.output);

    return {
      translated,
      sourceLang: input.sourceLang,
      targetLang: input.targetLang,
      provider: response.provider || 'unknown',
      tokens: response.tokens
    };
  }
}
