// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { TranslationFactory } from '../../../core/factories/TranslationFactory';

const factory = new TranslationFactory();

export async function detectLanguage(text: string): Promise<string> {
  // Use the translation factory with a language detection prompt
  const input = {
    text: `Detect the language of the following text and return only the ISO 639-1 language code:\n\n${text}`,
    targetLang: 'en'
  };

  const result = await factory.run(input);
  // Extract language code from response (simplified - would need more sophisticated parsing)
  const detectedLang = result.translated.trim().toLowerCase();

  // Return common defaults if detection fails
  return detectedLang.length === 2 ? detectedLang : 'en';
}
