// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { TranslationFactory } from '../../../core/factories/TranslationFactory';

const factory = new TranslationFactory();

export async function formatTranslation(text: string, targetFormat?: string): Promise<string> {
  if (!targetFormat) {
    return text; // No formatting requested
  }

  const input = {
    text: `Format the following text in ${targetFormat} style while preserving meaning:\n\n${text}`,
    targetLang: 'en' // Formatting is typically done in the same language
  };

  const result = await factory.run(input);
  return result.translated;
}

export function preserveFormatting(text: string): string {
  // Basic formatting preservation - replace common markdown patterns
  return text
    .replace(/\*\*(.*?)\*\*/g, '**$1**') // Bold
    .replace(/\*(.*?)\*/g, '*$1*')       // Italic
    .replace(/```([\s\S]*?)```/g, '```$1```') // Code blocks
    .replace(/`(.*?)`/g, '`$1`');        // Inline code
}
