// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { TranslationFactory } from '../../../core/factories/TranslationFactory';

const factory = new TranslationFactory();

export interface GlossaryEntry {
  source: string;
  target: string;
  context?: string;
}

export async function handleGlossary(
  text: string,
  glossary: GlossaryEntry[],
  targetLang: string
): Promise<string> {
  if (!glossary || glossary.length === 0) {
    return text;
  }

  // Build glossary context
  const glossaryContext = glossary
    .map(entry => `${entry.source} → ${entry.target}${entry.context ? ` (${entry.context})` : ''}`)
    .join('\n');

  const input = {
    text: `Translate the following text to ${targetLang}, using this glossary for terminology:\n\nGLOSSARY:\n${glossaryContext}\n\nTEXT TO TRANSLATE:\n${text}`,
    targetLang
  };

  const result = await factory.run(input);
  return result.translated;
}

export function applyGlossaryDirect(text: string, glossary: GlossaryEntry[]): string {
  let result = text;
  for (const entry of glossary) {
    // Simple direct replacement (case-insensitive)
    const regex = new RegExp(`\\b${entry.source}\\b`, 'gi');
    result = result.replace(regex, entry.target);
  }
  return result;
}
