// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { TranslationFactory } from '../../../core/factories/TranslationFactory';
import { TranslationInput, TranslationOutput } from '../../../types';

const factory = new TranslationFactory();

export async function translateText(
  text: string,
  targetLang: string,
  sourceLang?: string,
  preserveFormat?: boolean
): Promise<string> {
  const input: TranslationInput = {
    text,
    targetLang,
    sourceLang,
    preserveFormat
  };

  const result: TranslationOutput = await factory.run(input);
  return result.translated;
}
