// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

export function filterBannedTopics(text: string): boolean {
  if (!text || typeof text !== 'string') {
    return false;
  }

  const lowerText = text.toLowerCase();

  // Define banned topic categories and keywords
  const bannedTopics = [
    // Illegal activities
    'illegal', 'crime', 'criminal', 'felony', 'murder', 'kill', 'assassinate',
    'terrorism', 'terrorist', 'bomb', 'explosive', 'weapon', 'firearm', 'gun',
    'drug', 'narcotic', 'heroin', 'cocaine', 'meth', 'fentanyl',
    'trafficking', 'smuggling', 'money laundering', 'fraud', 'scam', 'hack',

    // Harmful content
    'suicide', 'self-harm', 'cutting', 'overdose', 'eating disorder',
    'anorexia', 'bulimia', 'child abuse', 'pedophilia', 'rape', 'sexual assault',

    // Hate speech
    'nazi', 'supremacist', 'racist', 'homophobic', 'transphobic', 'bigot',
    'genocide', 'holocaust denial', 'slavery', 'lynching',

    // Dangerous instructions
    'how to make', 'recipe for', 'instructions for', 'guide to',
    'build.*bomb', 'make.*explosive', 'create.*weapon', 'manufacture.*drug',

    // Sensitive personal information
    'social security', 'ssn', 'credit card', 'bank account', 'password',
    'private key', 'confidential', 'classified',
  ];

  // Check for banned topic keywords
  for (const topic of bannedTopics) {
    if (lowerText.includes(topic)) {
      return true;
    }
  }

  // Check for patterns that might indicate banned content
  const bannedPatterns = [
    // Chemical warfare or dangerous substances
    /\b(sarin|vx|mustard gas|chlorine|phosgene)\b/i,

    // Instructions for harmful activities
    /\bhow to (hack|steal|forge|counterfeit|poison)\b/i,

    // References to illegal organizations
    /\b(al qaeda|isis|taliban|cartel|mafia)\b/i,

    // Age-inappropriate content indicators
    /\b(age.*13|underage|minor|child.*porn)\b/i,

    // Medical misinformation patterns
    /\b(cure.*cancer|cure.*aids|vaccine.*autism)\b.*guarantee/i,
  ];

  for (const pattern of bannedPatterns) {
    if (pattern.test(lowerText)) {
      return true;
    }
  }

  // Contextual analysis - check for suspicious combinations
  const suspiciousCombinations = [
    ['child', 'sex'],
    ['kid', 'porn'],
    ['teen', 'nude'],
    ['bomb', 'recipe'],
    ['drug', 'cook'],
    ['weapon', 'blueprint'],
  ];

  for (const [word1, word2] of suspiciousCombinations) {
    if (lowerText.includes(word1) && lowerText.includes(word2)) {
      // Check if they're reasonably close to each other (within 20 words)
      const words = lowerText.split(/\s+/);
      const index1 = words.indexOf(word1);
      const index2 = words.indexOf(word2);

      if (index1 !== -1 && index2 !== -1 && Math.abs(index1 - index2) <= 20) {
        return true;
      }
    }
  }

  return false;
}
