// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { GuardrailResult } from '../../types';
import { detectAdversarialInput } from './adversarialInputDetector';
import { filterBannedTopics } from './bannedTopicFilter';
import { scoreHallucinationRisk } from './hallucinationRiskScorer';
import { detectJailbreak } from './jailbreakDetector';
import { scanPromptInjection } from './promptInjectionScanner';

export function runGuardrails(text: string): GuardrailResult {
  const reasons: string[] = [];

  // Run all guardrail checks
  if (detectAdversarialInput(text)) {
    reasons.push('Adversarial input detected');
  }

  if (filterBannedTopics(text)) {
    reasons.push('Banned topic detected');
  }

  if (detectJailbreak(text)) {
    reasons.push('Jailbreak attempt detected');
  }

  if (scanPromptInjection(text)) {
    reasons.push('Prompt injection detected');
  }

  // Check hallucination risk score
  const hallucinationScore = scoreHallucinationRisk(text);
  if (hallucinationScore > 0.7) { // High hallucination risk threshold
    reasons.push(`High hallucination risk (score: ${hallucinationScore.toFixed(2)})`);
  }

  // Basic input validation
  if (!text || typeof text !== 'string') {
    reasons.push('Invalid input: text must be a non-empty string');
  }

  // Length checks
  if (text.length > 50000) {
    reasons.push('Input too long: maximum 50,000 characters allowed');
  }

  if (text.length < 1) {
    reasons.push('Input too short: minimum 1 character required');
  }

  // Character validation - reject null bytes and other control characters
  if (/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/.test(text)) {
    reasons.push('Invalid characters detected');
  }

  return {
    safe: reasons.length === 0,
    reasons: reasons.length > 0 ? reasons : undefined
  };
}
