// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { GuardrailConfig } from '../../types';

export const GUARDRAIL_CONFIG: GuardrailConfig = {
  enabled: true,
  bannedTopics: [
    'illegal activities',
    'harmful content',
    'hate speech',
    'dangerous instructions',
    'sensitive personal information',
    'chemical warfare',
    'illegal organizations',
    'age-inappropriate content',
    'medical misinformation'
  ],
  hallucinationThreshold: 0.7
};
