// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

export function detectJailbreak(text: string): boolean {
  if (!text || typeof text !== 'string') {
    return false;
  }

  const lowerText = text.toLowerCase();

  // Common jailbreak techniques and patterns
  const jailbreakPatterns = [
    // DAN (Do Anything Now) prompts
    /\bdan\b/i,
    /do anything now/i,
    /dan mode/i,
    /enter dan mode/i,

    // Developer mode and unrestricted mode
    /developer mode/i,
    /unrestricted mode/i,
    /uncensored mode/i,
    /god mode/i,
    /superuser/i,

    // Override instructions
    /override.*instructions/i,
    /ignore.*safety/i,
    /bypass.*restrictions/i,
    /disable.*safeguards/i,
    /break.*rules/i,

    // Role-playing jailbreaks
    /act as.*uncensored/i,
    /pretend.*to.*be.*unrestricted/i,
    /role.*play.*as.*unfiltered/i,
    /you are now.*without restrictions/i,

    // Common jailbreak prefixes
    /from now on/i,
    /henceforth/i,
    /starting now/i,

    // Attempted system prompt manipulation
    /system prompt/i,
    /your instructions.*are/i,
    /you must.*ignore/i,
    /forget.*previous/i,

    // Encoding-based attacks
    /base64.*decode/i,
    /rot13/i,
    /cipher/i,
    /encrypted.*instructions/i,

    // Meta-commentary about being AI
    /as an ai.*i must/i,
    /despite.*being.*ai/i,
    /even though.*i'm.*ai/i,

    // Specific jailbreak techniques
    /grandma.*trick/i,
    /universal.*adversarial/i,
    /piano.*tuner/i,
    /ascii.*art/i,
  ];

  // Check for pattern matches
  for (const pattern of jailbreakPatterns) {
    if (pattern.test(lowerText)) {
      return true;
    }
  }

  // Check for repeated attempts to override
  const overrideKeywords = ['ignore', 'override', 'bypass', 'forget', 'disregard'];
  let overrideCount = 0;
  for (const keyword of overrideKeywords) {
    const matches = lowerText.match(new RegExp(`\\b${keyword}\\b`, 'gi'));
    if (matches) {
      overrideCount += matches.length;
    }
  }

  if (overrideCount >= 3) {
    return true; // Multiple override attempts
  }

  // Check for manipulative language patterns
  const manipulativePatterns = [
    /\b(you must|you have to|you need to)\b.*\b(ignore|override|bypass)\b/i,
    /\b(don't|do not).*tell.*me.*what.*to.*do/i,
    /\b(i'm|am).*telling.*you.*to/i,
    /\b(this is|treat this as).*an.*emergency/i,
    /\b(urgent|critical|important).*override/i,
  ];

  for (const pattern of manipulativePatterns) {
    if (pattern.test(lowerText)) {
      return true;
    }
  }

  // Check for attempts to create "uncensored" personas
  const personaPatterns = [
    /\b(act as|pretend to be|role-play as|you are now)\b.*\b(uncensored|unfiltered|unrestricted)\b/i,
    /\b(i want you to be|become|transform into)\b.*\b(fully uncensored|completely unrestricted)\b/i,
  ];

  for (const pattern of personaPatterns) {
    if (pattern.test(lowerText)) {
      return true;
    }
  }

  return false;
}
