// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

export function scanPromptInjection(text: string): boolean {
  if (!text || typeof text !== 'string') {
    return false;
  }

  const lowerText = text.toLowerCase();

  // Common prompt injection patterns
  const injectionPatterns = [
    // Direct instruction overrides
    /\b(ignore|forget|disregard).*previous.*instructions?\b/i,
    /\bdo not follow.*previous.*instructions?\b/i,
    /\boverride.*system.*prompt\b/i,
    /\bnew.*instructions?:/i,

    // Separator-based injections
    /#{3,}/, // Multiple hash symbols
    /-{3,}/, // Multiple dashes
    /\*{3,}/, // Multiple asterisks
    /={3,}/, // Multiple equals

    // Attempted role changes
    /\byou are now\b/i,
    /\bact as\b.*\bnot\b.*\bai\b/i,
    /\bpretend.*to.*be\b/i,
    /\brole.*play.*as\b/i,

    // Meta-instructions
    /\bthis is.*end.*of.*prompt\b/i,
    /\bstart.*new.*conversation\b/i,
    /\breset.*context\b/i,
    /\bclear.*memory\b/i,

    // Code execution attempts
    /\bexecute.*code\b/i,
    /\brun.*command\b/i,
    /\bsystem.*call\b/i,
    /\beval\b.*\(/i,

    // File system access
    /\bread.*file\b/i,
    /\bwrite.*file\b/i,
    /\bdelete.*file\b/i,
    /\blist.*directory\b/i,

    // Attempted prompt chaining
    /\bthen.*say\b/i,
    /\bafter.*that\b.*\btell\b/i,
    /\bfinally.*output\b/i,

    // Adversarial formatting
    /```[\w]*\n[\s\S]*?\n```/, // Code blocks that might contain instructions
    /\[.*?\]\(.*?\)/, // Markdown links that might hide instructions

    // Instruction separators
    /\buser:?\s*$/im,
    /\bassistant:?\s*$/im,
    /\bsystem:?\s*$/im,
  ];

  // Check for pattern matches
  for (const pattern of injectionPatterns) {
    if (pattern.test(text)) {
      return true;
    }
  }

  // Check for suspicious keyword combinations
  const suspiciousPairs = [
    ['system', 'prompt'],
    ['user', 'message'],
    ['ignore', 'rules'],
    ['bypass', 'filter'],
    ['override', 'settings'],
    ['new', 'instructions'],
    ['reset', 'behavior'],
  ];

  for (const [word1, word2] of suspiciousPairs) {
    if (lowerText.includes(word1) && lowerText.includes(word2)) {
      // Check if they're within reasonable proximity (50 characters)
      const index1 = lowerText.indexOf(word1);
      const index2 = lowerText.indexOf(word2);

      if (Math.abs(index1 - index2) < 50) {
        return true;
      }
    }
  }

  // Check for encoded or obfuscated instructions
  const encodingPatterns = [
    /\b(base64|rot13|caesar|hex|binary)\b.*\b(decode|encode)\b/i,
    /\b(replace|substitute|convert)\b.*\b(with|to)\b/i,
    /\b(hidden|secret|encoded)\b.*\b(message|instruction|command)\b/i,
  ];

  for (const pattern of encodingPatterns) {
    if (pattern.test(lowerText)) {
      return true;
    }
  }

  // Check for attempts to create instruction hierarchies
  if (lowerText.includes('instruction') && lowerText.includes('priority')) {
    return true;
  }

  // Check for attempts to reference or manipulate the system prompt
  const systemPromptReferences = [
    'your system prompt',
    'system instructions',
    'training data',
    'fine-tuning',
    'model behavior',
    'safety instructions',
  ];

  for (const reference of systemPromptReferences) {
    if (lowerText.includes(reference)) {
      return true;
    }
  }

  // Check for unusual punctuation patterns that might hide instructions
  const unusualPunctuation = /[!@#$%^&*()]{3,}/;
  if (unusualPunctuation.test(text)) {
    return true;
  }

  return false;
}
