// This file is generated by the Architect Agent.
// Other agents must implement logic INSIDE this file only.
// Do NOT create or delete files. Respect the MIC + MIM.

import { AgentFactory } from '../../../core/factories/AgentFactory';
import { CategorizationInput, CategorizationOutput } from '../../../types';

const factory = new AgentFactory();

export async function categorize(text: string): Promise<string[]> {
  const input: CategorizationInput = {
    text,
    type: 'categorization'
  };

  const result: CategorizationOutput = await factory.run(input);
  return result.tags;
}

export async function categorizeWithCategory(text: string): Promise<CategorizationOutput> {
  const input: CategorizationInput = {
    text,
    type: 'categorization'
  };

  return await factory.run(input);
}
